version: 2
jobs:
  asan:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: ./ci/install_dependencies.sh
      - run: ./ci/do_ci.sh cmake.asan

workflows:
  version: 2
  all:
    jobs:
      - asan
